ftp_server:
  image: stilliard/pure-ftpd:hardened
  container_name: ftp-server
  ports:
    - "21:21"
    - "30000-30009:30000-30009"
  volumes:
    - "./files/ftp/data:/home/username/"
    - "./files/ftp/passwd:/etc/pure-ftpd/passwd"
  environment:
    PUBLICHOST: "localhost"
    FTP_USER_NAME: "java"
    FTP_USER_PASS: "java"
    FTP_USER_HOME: /home/test/desafio/ftpserver/servidorFTP
  restart: always

  mongo_db:
    image: mongo
    container_name: mongo-db
    volumes:
      - "./files/db/mongo:/data"
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      AUTH: "no"