version: '2'

services:
  server_web:
    image: viniciusp/ftpserver
    container_name: "webserver"
    network_mode: host
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - /home/ubuntu/docker-mongo:/data/db
    ports:
      - 27017:27017
    network_mode: host